name: deploy
on:
  push:
    branches:
      - main


jobs:
    deploy_lambda:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up node js
          uses: actions/setup-node@v2
          with:
            node-version: '12'

        - name: Install npm
          run: |
            npm ci
